CREATE TABLE TALUNO
(
  COD_ALUNO INTEGER NOT NULL,
  NOME VARCHAR(30),
  CIDADE VARCHAR2(30),
  CEP VARCHAR(10),
  PRIMARY KEY (COD_ALUNO)
);

SELECT *FROM TALUNO;

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (1,'SABRYNA','GUARULHOS','8908000');

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (2,'TONY','SAO PAULO','4590000');

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (3,'MARIA','BAHIA','3467000');

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (4,'MARTA','ARUJA','2356000');

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (5,'GAEL','SANTO ANDRE','7869000');



CREATE TABLE TCURSO
(
 COD_CURSO INTEGER NOT NULL PRIMARY KEY,
 NOME VARCHAR(30),
 VALOR NUMBER(8,2),
 CARGA_HORARIA INTEGER
);

 SELECT * FROM TCURSO;

INSERT INTO TCURSO VALUES (1,'ORACLE SQL E PL/SQL',700,25);
INSERT INTO TCURSO VALUES (2,'ORECLE DBA',500,25);
INSERT INTO TCURSO VALUES (3,'JAVA FUNDAMENTOS',1200,100);
INSERT INTO TCURSO VALUES (4,'REACT',600,50);



CREATE TABLE TCONTRATO
(
  COD_CONTRATO INTEGER NOT NULL PRIMARY KEY,
  DATA DATE,
  COD_ALUNO INTEGER,
  TOTAL NUMBER(8,2),
  DESCONTO NUMBER(5,2)
);

SELECT * FROM TCONTRATO;

INSERT INTO TCONTRATO VALUES (1,SYSDATE  ,1,700,15);
INSERT INTO TCONTRATO VALUES (2,SYSDATE  ,2,500,05);
INSERT INTO TCONTRATO VALUES (3,SYSDATE  ,3,1200,20);
INSERT INTO TCONTRATO VALUES (4,SYSDATE-5,2,600,05);
INSERT INTO TCONTRATO VALUES (5,SYSDATE-4,3,600,15);
INSERT INTO TCONTRATO VALUES (6,SYSDATE-3,4,700,10);
INSERT INTO TCONTRATO VALUES (7,SYSDATE-2,5,1200,20);

--Inserir uma coluna na tabela
ALTER TABLE TCONTRATO ADD COL_TESTE VARCHAR(50);

SELECT * FROM TCONTRATO;

--Excluir coluna da tabela
ALTER TABLE TCONTRATO DROP COLUMN COL_TESTE;

--Alterar nome de coluna
ALTER TABLE TALUNO RENAME COLUMN NOME TO NOME2;
ALTER TABLE TALUNO RENAME COLUMN NOME2 TO NOME;

--Excluir a tabela
DROP TABLE TABELA;

--Sequence
CREATE SEQUENCE SEQ_CURSO START WITH 5;

INSERT INTO TCURSO VALUES (SEQ_CURSO.NEXTVAL,'JAVA SCRIPT','800',48);

INSERT INTO TCURSO VALUES (SEQ_CURSO.NEXTVAL,'PYTHON',1500,130);

SELECT * FROM TCURSO;

--Data/hora atual
SELECT SYSDATE FROM DUAL;

--
SELECT * FROM DUAL;

--Valor atual da sequence
SELECT SEQ_ALUNO.CURRVAL FROM DUAL;


--Confirma alteracoes realizadas (insert, update e delete)
COMMIT;

SELECT * FROM TALUNO;

DELETE FROM TALUNO;

--Desfaz alteracoes realizadas (insert, update e delete)
ROLLBACK;

--Excluir registro da tabela
SELECT * FROM TALUNO;

DELETE FROM TALUNO;
WHERE COD_ALUNO = 5;

SELECT * FROM TALUNO;

ROLLBACK;

SELECT * FROM TALUNO WHERE NOME = 'GAEL';

DELETE FROM TALUNO WHERE NOME = 'GAEL';

COMMIT;

ROLLBACK;



CREATE TABLE TGESTAO
(
 COD_GESTAO INTEGER NOT NULL PRIMARY KEY,
 COD_CURSO INTEGER,
 COD_CONTRATO INTEGER,
 PAGEMENTO NUMBER(8,2)
);

 SELECT * FROM TGESTAO


INSERT INTO TGESTAO VALUES (1, 1, 1, 500);
INSERT INTO TGESTAO VALUES (2, 1, 2, 700);
INSERT INTO TGESTAO VALUES (3, 2, 3, 1200);
INSERT INTO TGESTAO VALUES (4, 3, 4, 600);
INSERT INTO TGESTAO VALUES (5, 1, 5, 800);
INSERT INTO TGESTAO VALUES (6, 2, 6, 1500);


COMMIT;

SELECT * FROM TGESTAO


SELECT * FROM TCONTRATO
WHERE COD_CONTRATO = 2;

--Alertar registro da tabela
UPDATE TCONTRATO SET
  DESCONTO = 18
WHERE COD_CONTRATO = 2;

SELECT * FROM TALUNO;

UPDATE TALUNO SET
 CIDADE = 'BAHIA'
WHERE Upper(CIDADE) = 'SALVADOR';


