SELECT * FROM TALUNO
WHERE ESTADO <> 'BA'
AND SALARIO <= 800
ORDER BY SALARIO DESC;

COMMIT;

INSERT INTO TALUNO (COD_ALUNO,NOME,CIDADE)
VALUES (SEQ_ALUNO.NEXTVAL,'VALDO','ARRAIAL DO CABO');

INSERT INTO TALUNO (COD_ALUNO,NOME,CIDADE)
VALUES (SEQ_ALUNO.NEXTVAL,'LAURA','BELO HORIZONTE');

SELECT * FROM TALUNO;


UPDATE TALUNO SET
ESTADO = 'RJ', SALARIO = 900, NOME = 'MARIANA'
WHERE COD_ALUNO = 46;

UPDATE TALUNO SET
ESTADO = 'MG'
WHERE COD_ALUNO = 47;


--
DELETE FROM TALUNO WHERE COD_ALUNO = 49;

--

SELECT ESTADO, SALARIO, NOME FROM TALUNO
ORDER BY ESTADO, SALARIO DESC;

ALTER TABLE TALUNO ADD NASCIMENTO DATE DEFAULT SYSDATE -1500;

SELECT SYSDATE - SYSDATE - 20 FROM DUAL;

--
SELECT * FROM TALUNO

UPDATE TALUNO SET
NASCIMENTO = SYSDATE -10
WHERE COD_ALUNO = 3;


UPDATE TALUNO SET
NASCIMENTO = SYSDATE -100
WHERE COD_ALUNO = 47;

UPDATE TALUNO SET
NASCIMENTO = SYSDATE -300
WHERE COD_ALUNO = 1;

UPDATE TALUNO SET
NASCIMENTO = SYSDATE -800
WHERE COD_ALUNO = 4;


--
SELECT * FROM TALUNO

SELECT COD_ALUNO, NASCIMENTO, Trunc(NASCIMENTO), NOME
FROM TALUNO
WHERE Trunc(NASCIMENTO) = '05/02/2019';


SELECT COD_ALUNO, NASCIMENTO, Trunc(NASCIMENTO), NOME
FROM TALUNO
WHERE NASCIMENTO
   BETWEEN TO_DATE ('05/02/2019 15:00','DD/MM/YYYY HH24:MI')
   AND TO_DATE('05/02/2019 17:00','DD/MM/YYYY HH24:MI')


SELECT COD_CONTRATO, DATA, TOTAL,
      DESCONTO, DESCONTO + 1000 AS CALCULO
FROM TCONTRATO
WHERE TOTAL <= DESCONTO + 1000;

--
SELECT * FROM TCONTRATO;

--
UPDATE TCONTRATO SET
DESCONTO = NULL
WHERE COD_CONTRATO = 2;
--

SELECT * FROM TCONTRATO
WHERE DESCONTO IS NULL;
--

SELECT * FROM TCONTRATO
WHERE DESCONTO IS NOT NULL;
--

SELECT * FROM TCONTRATO
WHERE DESCONTO BETWEEN 0 AND 10;


--NLV 0 ->Colunas com valor NULL
--BETWEEN -> Entre
SELECT COD_CONTRATO, TOTAL, DESCONTO, NVL(DESCONTO,0)
FROM TCONTRATO
WHERE Nvl(DESCONTO,0) BETWEEN 0 AND 10;

--Mesmo efeito do between

SELECT * FROM TCONTRATO
WHERE DESCONTO >= 0
AND DESCONTO <= 10
OR DESCONTO IS NULL;


-- IN /// NOT IN
SELECT * FROM TGESTAO
WHERE COD_CURSO IN (1, 2, 3);

SELECT * FROM TGESTAO
WHERE COD_CURSO NOT IN (5, 2, 4);

SELECT * FROM TCURSO;

INSERT INTO TCURSO VALUES (7, 'WINDOWS', 1400, 50);

--Cursos nao vendidos
SELECT * FROM TCURSO
WHERE COD_CURSO NOT IN (SELECT COD_CURSO FROM TGESTAO);


--Cursos vendidos
SELECT * FROM TCURSO
WHERE COD_CURSO IN (SELECT COD_CURSO FROM TGESTAO);


--Equivalente ao SELECT IN
SELECT * FROM TGESTAO
WHERE COD_CURSO = 1
OR COD_CURSO = 2
OR COD_CURSO = 4;


--Somente onde a segunda letra seja A
SELECT * FROM TALUNO WHERE NOME LIKE 'M%' -- % -> registros que inicia com M
SELECT * FROM TCURSO WHERE NOME LIKE '%JAVA%'
SELECT * FROM TCURSO WHERE NOME LIKE '%SCRIPT'

SELECT * FROM TCURSO;

COMMIT;

ALTER TABLE TCURSO ADD PRE_REQ INTEGER;

UPDATE TCURSO SET
PRE_REQ = 1
WHERE COD_CURSO = 2;

UPDATE TCURSO SET
PRE_REQ = 7
WHERE COD_CURSO = 4;

UPDATE TCURSO SET
PRE_REQ =5
WHERE COD_CURSO = 3;

SELECT * FROM TCURSO;

--Cursos sem pre requisito
SELECT * FROM TCURSO WHERE PRE_REQ IS NULL

--Curso com pre requisito
SELECT * FROM TCURSO WHERE PRE_REQ IS NOT NULL
--

--Precedencia de operadores
--()
--AND
--OR
SELECT * FROM TCURSO
WHERE VALOR > 700
OR VALOR < 1000
AND CARGA_HORARIA = 25
--

SELECT * FROM TCURSO
WHERE (VALOR > 700
OR VALOR < 1000)
AND CARGA_HORARIA = 25;

COMMIT;


