SELECT * FROM TALUNO;

SELECT * FROM TCONTRATO;

--Produto cartesiano -> ERRADO
SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO


--Correto
SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO
WHERE TALUNO.COD_ALUNO = TCONTRATO.COD_ALUNO


--Coluna ambigua -> ERRADO
SELECT COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO
WHERE TALUNO.COD_ALUNO = TALUNO.COD_ALUNO

--Correto, quando uma coluna existe com mesmo nome em mais de uma tabela,
--colocar prefixo na coluna
SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO
WHERE TALUNO.COD_ALUNO = TALUNO.COD_ALUNO


--Uniao da tabela de aluno com contrato
SELECT ALU.COD_ALUNO, ALU.NOME AS ALUNO,
       CON.COD_CONTRATO, CON.DATA, CON.TOTAL

FROM TALUNO ALU, TCONTRATO CON

WHERE CON.COD_ALUNO = ALU.COD_ALUNO

AND Upper (ALU.NOME) LIKE '%'

ORDER BY ALU.NOME


SELECT * FROM TALUNO
SELECT * FROM TCONTRATO
SELECT * FROM TGESTAO
SELECT * FROM TCURSO

SELECT ALU.COD_ALUNO, ALU.NOME AS ALUNO,
       CON.COD_CONTRATO, CON.DATA, CON.TOTAL,
       GES.COD_CURSO, CUR.NOME AS CURSO,
       GES.PAGAMENTO

FROM TALUNO ALU, TCONTRATO CON,
     TGESTAO GES, TCURSO CUR

WHERE ALU.COD_ALUNO = CON.COD_ALUNO
AND   CON.COD_CONTRATO = GES.COD_CONTRATO
AND   GES.COD_CURSO = CUR.COD_CURSO

ORDER BY CON.TOTAL DESC;


 --------------------------
CREATE TABLE TDESCONTO
( CLASSE VARCHAR(1) PRIMARY KEY,
  INFERIOR NUMBER(4,2),
  SUPERIOR NUMBER (4,2)
);

INSERT INTO TDESCONTO VALUES ('A',00,10);
INSERT INTO TDESCONTO VALUES ('B',11,15);
INSERT INTO TDESCONTO VALUES ('C',16,20);
INSERT INTO TDESCONTO VALUES ('D',21,25);
INSERT INTO TDESCONTO VALUES ('E',26,30);

SELECT * FROM TDESCONTO;


COMMIT;

------------------------

SELECT * FROM TCONTRATO

UPDATE TCONTRATO SET
DESCONTO = 27
WHERE COD_CONTRATO = 2;


UPDATE TCONTRATO SET
DESCONTO = 30
WHERE COD_CONTRATO = 4;

-------------------------------------
SELECT CON.COD_CONTRATO AS CONTRATO, CON.DESCONTO,
       DES.CLASSE AS DESCONTO

FROM TCONTRATO CON, TDESCONTO DES
WHERE CON.DESCONTO BETWEEN DES.INFERIOR AND DES. SUPERIOR

ORDER BY CON.COD_CONTRATO;

--Mostrar cursos mais vendidos
SELECT CUR.COD_CURSO, CUR.NOME, GES.COD_GESTAO
FROM TCURSO CUR, TGESTAO GES
WHERE CUR.COD_CURSO = GES.COD_CURSO


-- Mostrar cursos nao vendidos
SELECT CUR.COD_CURSO, CUR.NOME,GES.COD_GESTAO
FROM TCURSO CUR, TGESTAO GES
WHERE CUR.COD_CURSO = GES.COD_CURSO(+)
AND GES.COD_GESTAO IS NULL;


SELECT * FROM TCURSO;


UPDATE TCURSO SET PRE_REQ = 7
WHERE COD_CURSO = 6

UPDATE TCURSO SET PRE_REQ = 3
WHERE COD_CURSO = 5

UPDATE TCURSO SET PRE_REQ = 2
WHERE COD_CURSO = 1


--Select de duas tabelas (a mesma tabela)
SELECT CURSO.NOME AS CURSO,
       PRE_REQ.NOME AS PRE_REQUISITO

FROM TCURSO CURSO, TCURSO PRE_REQ
WHERE CURSO.PRE_REQ = PRE_REQ.COD_CURSO(+);

COMMIT;
