CREATE TABLE TESTE
(CODIGO INTEGER NOT NULL PRIMARY KEY,
  DATA DATE DEFAULT SYSDATE
);

INSERT INTO TESTE (CODIGO) VALUES (1);


SELECT * FROM TESTE;


--Tipos de Dados
VARCHAR2(10) -> 'PEDRO'
CHAR(10) -> 'PEDRO     '

NUMBER(5,2) -> 999.99


--tabelas criadas pelo usuario -USER_TABLES(View)
SELECT * FROM USER_TABLES;

SELECT * FROM ALL_TABLES;


CREATE TABLE TCONTRATO_VIP
AS
 SELECT * FROM TCONTRATO WHERE TOTAL > 500;

SELECT * FROM TCONTRATO_VIP;


--Add coluna na tabela
ALTER TABLE TCONTRATO_VIP ADD VALOR NUMBER(5,2);

--Alterar coluna
ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(8,2);

--Alterar coluna
ALTER TABLE TCONTRATO_VIP MODIFY VALOR NUMBER(12,2); DEFAULT 0;

--Renomear coluna
ALTER TABLE TCONTRATO_VIP RENAME COLUMN VALOR TO VALOR2;

--Excluir cluna
ALTER TABLE TCONTRATO_VIP DROP COLUMN VALOR2;

--Excluir coluna
DROP TABLE TCONTRATO_VIP
DROP TABLE TITEM;

--Renomear tabela
RENAME TCONTRATO TO TCONTRATO_TOP;

SELECT * FROM TCONTRATO_TOP;

RENAME TCONTRATO_TOP TO TCONTRATO;

SELECT * FROM TCONTRATO;


--Comentatio na tabela
COMMENT ON TABLE TCONTRATO IS 'Informacao de Contratos';

--Comentario na coluna da tabela
COMMENT ON COLUMN TCONTRATO.COD_CONTRATO IS 'Codigo de Contrato';

COMMENT ON COLUMN TCONTRATO.DATA IS 'Data de emissao do Contrato';

SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME = 'TCONTRATO';

SELECT * FROM USER_TAB_COMMENTS WHERE TABLE_NAME = 'TCONTRATO';


--Desabilita coluna
ALTER TABLE TCONTRATO ADD TOTAL2 NUMERIC(8,2);

ALTER TABLE TCONTRATO SET UNUSED (TOTAL2);

SELECT * FROM TCONTRATO;

--Excluir colunas nao usadas
ALTER TABLE TCONTRATO DROP UNUSED COLUMNS;


--TRUNCATE TABLE -> esclui todos os registros da tabela
--Nao tem WHERE nem COMMIT/ROLLBACK
TRUNCATE TABLE TESTE;

COMMIT;
